version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bank_authenticator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /Users/nicomarbonkoskifilho/coding/bank-authenticator/postgres_data:/var/lib/postgresql/data